version: '3.8'

services:

  # Main Backend Application Configurations
  base:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    #    command: '/bin/sh'
    volumes:
      - ./elocart/:/usr/src/elocart/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  # Database Configurations
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
volumes:
  postgres_data: