version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app
    ports:
      - 80:8000
    env_file:
      - ./.env.dev.local
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.local

volumes:
  postgres_data:
